<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 reduced.glb
Author: Jakub.Vildomec (https://sketchfab.com/Jakub.Vildomec)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mcrn-tachi-expanse-tv-show-76fc983ab08c449b9042491a00e621cf
Title: MCRN Tachi [Expanse TV Show]
-->
<script>
  import { Group } from 'three'
  import { T, Three } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const { gltf } = useGltf('https://alexwarnes.github.io/assets/models/rocinante/roci-reduced.glb', {
    useDraco: true
  })
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Group position={[-70.13, 0.01, 69.36]} rotation={[-Math.PI / 2, 0, -0.33]} scale={100}>
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_body002_PDC_0.geometry}
        material={$gltf.materials.material}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_ammobox002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[-0.06, -0.04, 0.09]}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_doors_small002_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.17, -0.14, -0.12]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_large002_Primary_0.geometry}
        material={$gltf.materials.Primary}
        position={[0.06, 0.02, 0]}
        rotation={[1.57, -1.24, 1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_shielding002_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.08, -0.1, 0]}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_detail002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[-0.13, 0.08, 0]}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_barrels002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[-0.08, -0.01, 0]}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_barrels_holder002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[-0.02, -0.18, 0]}
        rotation={[-Math.PI / 2, -0.33, Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_sphere_holder002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[-0.13, -0.03, 0]}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_sphere002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[-0.12, -0.06, 0]}
        rotation={[-Math.PI / 2, -0.33, Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_ammobox_details002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[-0.06, -0.04, 0.09]}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_holders002_PDC_0.geometry}
        material={$gltf.materials.material}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_hodlers_details002_PDC_0.geometry}
        material={$gltf.materials.material}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_doors_large002_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.16, 0.06, -0.12]}
        rotation={[Math.PI, 0, -0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_hinge002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.12, -0.08, -0.11]}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_pistons002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.13, -0.08, -0.11]}
        rotation={[1.52, -1.24, -1.62]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_flat002_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.04, 0.01, 0]}
        rotation={[1.57, -1.24, 1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_small002_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.05, 0.02, 0]}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_base1002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.07, 0.03, -0.01]}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_base_details2002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.14, 0, 0]}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_swivel1002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[-0.02, 0.07, 0]}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_swivel2002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[-0.01, 0.09, 0.04]}
        rotation={[-Math.PI / 2, -1.02, Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_details002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[-0.01, 0.09, 0.04]}
        rotation={[-Math.PI / 2, -1.02, Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_base2002_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.07, 0.03, -0.01]}
        rotation={[Math.PI / 2, -1.24, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_body001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.29, 1.32, 0.55]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_ammobox001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.2, 1.3, 0.62]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_doors_small001_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.35, 1.53, 0.43]}
        rotation={[Math.PI / 2, -1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_large001_Primary_0.geometry}
        material={$gltf.materials.Primary}
        position={[0.29, 1.32, 0.49]}
        rotation={[0, 0, -2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_shielding001_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.25, 1.43, 0.5]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_detail001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.33, 1.21, 0.64]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_barrels001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.3, 1.3, 0.63]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_barrels_holder001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.24, 1.47, 0.63]}
        rotation={[1.57, 0.33, 0]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_sphere_holder001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.3, 1.3, 0.68]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_sphere001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.29, 1.33, 0.68]}
        rotation={[1.57, 0.33, 0]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_ammobox_details001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.2, 1.3, 0.62]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_holders001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.29, 1.32, 0.55]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_hodlers_details001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.29, 1.31, 0.55]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_doors_large001_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.41, 1.36, 0.37]}
        rotation={[-Math.PI / 2, 1.24, 1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_hinge001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.36, 1.46, 0.46]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_pistons001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.36, 1.47, 0.45]}
        rotation={[0.01, -0.02, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_flat001_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.29, 1.32, 0.51]}
        rotation={[0, 0, -2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_small001_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.29, 1.32, 0.49]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_base1001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.3, 1.31, 0.47]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_base_details2001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.28, 1.36, 0.42]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_swivel1001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.32, 1.25, 0.55]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_swivel2001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.28, 1.22, 0.53]}
        rotation={[0.85, 0.25, 0.21]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_details001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.28, 1.22, 0.53]}
        rotation={[0.85, 0.25, 0.21]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_base2001_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.3, 1.31, 0.47]}
        rotation={[0, 0, 0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_body003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.31, 1.32, -0.55]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_ammobox003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.39, 1.37, -0.62]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_doors_small003_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.13, 1.46, -0.44]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_large003_Primary_0.geometry}
        material={$gltf.materials.Primary}
        position={[0.31, 1.32, -0.49]}
        rotation={[3.14, 0, -0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_shielding003_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.27, 1.44, -0.51]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_detail003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.34, 1.21, -0.65]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_barrels003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.31, 1.31, -0.63]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_barrels_holder003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.25, 1.48, -0.63]}
        rotation={[1.57, 0.33, -3.14]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_sphere_holder003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.31, 1.31, -0.69]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_sphere003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.3, 1.33, -0.68]}
        rotation={[1.57, 0.33, -3.14]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_ammobox_details003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.39, 1.37, -0.62]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_holders003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.31, 1.32, -0.55]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_hodlers_details003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.31, 1.32, -0.55]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_doors_large003_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.19, 1.28, -0.37]}
        rotation={[Math.PI / 2, -1.24, 1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_hinge003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.16, 1.39, -0.46]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_pistons003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.16, 1.4, -0.45]}
        rotation={[-3.14, 0.02, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_flat003_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.31, 1.32, -0.51]}
        rotation={[3.14, 0, -0.33]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_small003_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.31, 1.32, -0.49]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_base1003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.3, 1.31, -0.47]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_base_details2003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.29, 1.36, -0.42]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_swivel1003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.33, 1.25, -0.55]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_swivel2003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.37, 1.25, -0.53]}
        rotation={[2.29, 0.25, 2.93]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_details003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.37, 1.25, -0.53]}
        rotation={[2.29, 0.25, 2.93]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_base2003_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.3, 1.31, -0.47]}
        rotation={[3.14, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_body004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.33, 0.45, 0]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_ammobox004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.4, 0.46, -0.09]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_doors_small004_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[1.28, 0.24, 0.12]}
        rotation={[-Math.PI, 0, 2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_large004_Primary_0.geometry}
        material={$gltf.materials.Primary}
        position={[1.27, 0.43, 0]}
        rotation={[-1.57, 1.24, 1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_shielding004_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[1.33, 0.32, 0]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_detail004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.38, 0.59, 0]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_barrels004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.4, 0.49, 0]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_barrels_holder004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.46, 0.32, 0]}
        rotation={[-Math.PI / 2, -0.33, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_sphere_holder004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.45, 0.51, 0]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_sphere004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.46, 0.48, 0]}
        rotation={[-Math.PI / 2, -0.33, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_ammobox_details004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.4, 0.46, -0.09]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_holders004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.33, 0.45, 0]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_hodlers_details004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.33, 0.45, 0]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_doors_large004_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[1.16, 0.4, 0.12]}
        rotation={[0, 0, -2.81]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_hinge004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.28, 0.31, 0.11]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_pistons004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.27, 0.3, 0.11]}
        rotation={[-1.63, 1.24, -1.52]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_flat004_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[1.29, 0.44, 0]}
        rotation={[-1.57, 1.24, 1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_small004_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[1.27, 0.43, 0]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_base1004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.25, 0.44, 0.01]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_base_details2004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.22, 0.37, 0]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_swivel1004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.31, 0.52, 0]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_swivel2004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.29, 0.53, -0.04]}
        rotation={[-Math.PI / 2, 0.37, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_details004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.29, 0.53, -0.04]}
        rotation={[-Math.PI / 2, 0.37, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_base2004_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.25, 0.44, 0.01]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_body006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.47, -0.78, -0.03]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_ammobox006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.54, -0.78, -0.13]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_doors_small006_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[1.33, -0.97, 0.09]}
        rotation={[-Math.PI, 0, 3.13]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_large006_Primary_0.geometry}
        material={$gltf.materials.Primary}
        position={[1.38, -0.78, -0.03]}
        rotation={[-1.57, 1.56, 1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_shielding006_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[1.4, -0.91, -0.03]}
        rotation={[-1.57, 1.56, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_detail006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.52, -0.64, -0.03]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_barrels006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.54, -0.74, -0.03]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_barrels_holder006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.6, -0.91, -0.03]}
        rotation={[-Math.PI / 2, -0.33, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_sphere_holder006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.59, -0.73, -0.03]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_sphere006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.6, -0.75, -0.03]}
        rotation={[-Math.PI / 2, -0.33, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_ammobox_details006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.54, -0.78, -0.13]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_holders006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.47, -0.78, -0.03]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_hodlers_details006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.47, -0.78, -0.03]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_doors_large006_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[1.26, -0.78, 0.09]}
        rotation={[0, 0, -3.13]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_hinge006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.35, -0.9, 0.08]}
        rotation={[-1.57, 1.56, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_pistons006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.34, -0.91, 0.08]}
        rotation={[-2.69, 1.55, -0.45]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_flat006_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[1.4, -0.78, -0.03]}
        rotation={[-1.57, 1.56, 1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_small006_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[1.38, -0.78, -0.03]}
        rotation={[-1.57, 1.56, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_base1006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.36, -0.77, -0.02]}
        rotation={[-1.57, 1.56, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_base_details2006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.33, -0.83, -0.03]}
        rotation={[-1.57, 1.56, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_swivel1006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.44, -0.71, -0.03]}
        rotation={[-Math.PI / 2, 1.24, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_swivel2006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.43, -0.69, -0.08]}
        rotation={[-Math.PI / 2, 0.63, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_details006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.42, -0.7, -0.08]}
        rotation={[-Math.PI / 2, 0.69, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_base2006_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[1.36, -0.77, -0.02]}
        rotation={[-1.57, 1.56, -1.57]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_body005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.64, -1.06, -0.03]}
        rotation={[Math.PI / 2, -1.25, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_ammobox005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.58, -1.11, 0.06]}
        rotation={[Math.PI / 2, -1.25, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_doors_small005_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.87, -1.13, -0.15]}
        rotation={[0, 0, 0.65]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_large005_Primary_0.geometry}
        material={$gltf.materials.Primary}
        position={[0.71, -1.01, -0.03]}
        rotation={[Math.PI / 2, -0.92, Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_shielding005_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.77, -1.12, -0.03]}
        rotation={[Math.PI / 2, -0.92, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_detail005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.51, -0.98, -0.03]}
        rotation={[Math.PI / 2, -1.25, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_barrels005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.56, -1.08, -0.03]}
        rotation={[Math.PI / 2, -1.25, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_barrels_holder005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.62, -1.25, -0.03]}
        rotation={[-Math.PI / 2, -0.32, Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_sphere_holder005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.51, -1.1, -0.03]}
        rotation={[Math.PI / 2, -1.25, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_sphere005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.52, -1.12, -0.03]}
        rotation={[-Math.PI / 2, -0.32, Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_ammobox_details005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.58, -1.11, 0.06]}
        rotation={[Math.PI / 2, -1.25, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_holders005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.64, -1.06, -0.03]}
        rotation={[Math.PI / 2, -1.25, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_hodlers_details005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.64, -1.06, -0.03]}
        rotation={[Math.PI / 2, -1.25, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_doors_large005_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.8, -0.94, -0.16]}
        rotation={[Math.PI, 0, -0.65]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_hinge005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.81, -1.08, -0.15]}
        rotation={[Math.PI / 2, -0.92, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_pistons005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.82, -1.08, -0.15]}
        rotation={[1.54, -0.92, -1.59]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_flat005_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.7, -1.02, -0.03]}
        rotation={[Math.PI / 2, -0.92, Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_small005_Secondary_0.geometry}
        material={$gltf.materials.Secondary}
        position={[0.71, -1.01, -0.03]}
        rotation={[Math.PI / 2, -0.92, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_base1005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.72, -0.99, -0.04]}
        rotation={[Math.PI / 2, -0.92, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_base_details2005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.78, -1.02, -0.04]}
        rotation={[Math.PI / 2, -0.92, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_swivel1005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.62, -0.99, -0.03]}
        rotation={[Math.PI / 2, -1.25, -Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_swivel2005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.62, -0.97, 0.01]}
        rotation={[-Math.PI / 2, -1.28, Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_gun_details005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.62, -0.97, 0.01]}
        rotation={[-Math.PI / 2, -1.34, Math.PI / 2]}
      />
      <T.Mesh
        geometry={$gltf.nodes.pdc_bay_base2005_PDC_0.geometry}
        material={$gltf.materials.material}
        position={[0.72, -0.99, -0.04]}
        rotation={[Math.PI / 2, -0.92, -Math.PI / 2]}
      />
    </T.Group>
    <T.Mesh
      geometry={$gltf.nodes.pdc_gun_details3_PDC_0.geometry}
      material={$gltf.materials.material}
      position={[-57.34, 0.01, 73.9]}
      rotation={[0, 0.69, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.pdc_gun_details3001_PDC_0.geometry}
      material={$gltf.materials.material}
      position={[-0.14, 41.86, -50.31]}
      rotation={[2.45, 0, Math.PI / 2]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.pdc_gun_details3002_PDC_0.geometry}
      material={$gltf.materials.material}
      position={[1.26, -42.1, -50.31]}
      rotation={[-2.45, 0, -Math.PI / 2]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.pdc_gun_details3003_PDC_0.geometry}
      material={$gltf.materials.material}
      position={[57.34, -0.01, 73.9]}
      rotation={[0, -0.69, Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.pdc_gun_details3005_PDC_0.geometry}
      material={$gltf.materials.material}
      position={[28.36, -3.44, 191.01]}
      rotation={[0, -0.96, Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.pdc_gun_details3004_PDC_0.geometry}
      material={$gltf.materials.material}
      position={[-28.36, -3.44, 191.01]}
      rotation={[0, 0.96, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_aft_Primary_0.geometry}
      material={$gltf.materials.Primary}
      position={[0, 0, -103.14]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_main_Primary_0.geometry}
      material={$gltf.materials.Primary}
      position={[0, 0, -103.14]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_Primary_0.geometry}
      material={$gltf.materials.Primary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_torpedo_bay_Primary_0.geometry}
      material={$gltf.materials.Primary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_rear_Primary_0.geometry}
      material={$gltf.materials.Primary}
      position={[0, 0.16, 56.71]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_main_accessory_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, -103.14]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_side_pipes_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-39.72, 30.16, -13.19]}
      rotation={[-Math.PI / 2, Math.PI / 4, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_topdown_pipes_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-31.12, 38.86, -13.19]}
      rotation={[Math.PI / 2, -Math.PI / 4, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.fuel_tanks_holder_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_topdown_accessory_11_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-22.71, 45.02, 0.55]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_topdown_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_side_accessory_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-0.87, 0.94, 56.71]}
      rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_side_accessory_21_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-45.91, 21.77, 0.52]}
      rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_side_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_topdown_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-0.98, -0.88, 56.71]}
      rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
      scale={[-100, 100, 100]}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_side_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-46.2, 21.74, -2.66]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_topdown_accessory_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-22.71, 45.31, -2.66]}
      rotation={[-Math.PI / 2, Math.PI / 2, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_front_bottom_part_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, -37.09, 123.52]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_topdown_accessory_22_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-22.7, -45.02, 0.55]}
      rotation={[Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.thruster_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 14.94, 222.68]}
      rotation={[-0.98, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.thruster_4_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-3.57, 10.42, 229.31]}
      rotation={[-0.98, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.thruster_5_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 3.08, 240.9]}
      rotation={[-1.46, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_main_accessory_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0.27, 25.25, 193.43]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.thruster_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 17.38, 214.87]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.thruster_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-6.69, 15.32, 218.19]}
      rotation={[-1.15, -0.57, 0.12]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.thruster_6_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, -0.61, 242.1]}
      rotation={[0.05, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_main_accessory_32_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0.27, 21.44, 203.63]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_main_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0.01, -0.17, -102.91]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_Primary_0.geometry}
      material={$gltf.materials.Primary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_6_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-56.91, 0.09, 38.63]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_front_bottom_part_Primary_0.geometry}
      material={$gltf.materials.Primary}
      position={[0, 0, 126.07]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_secondary_middle_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-44.38, -32.65, 42.81]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_Primary_0.geometry}
      material={$gltf.materials.Primary}
      position={[0, 0, 54.61]}
      rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_secondary_front_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-29.17, -26.02, 141.48]}
      rotation={[-1.57, -0.09, 0.19]}
      scale={71.62}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_accessory_6003_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-44.66, -0.01, -69.78]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_accessory_1001_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_5_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_accessory_2001_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_secondary_middle_accessory_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-47.37, -24.01, 50.28]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_secondary_middle_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-42.94, -27.76, 42.81]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_secondary_front_accessory_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-28.49, -22.44, 141.29]}
      rotation={[-1.57, -0.09, 0.19]}
      scale={71.62}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_secondary_rear_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-35.97, -36.33, -68.63]}
      rotation={[-1.45, 0.23, -0.31]}
      scale={71.58}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_secondary_rear_accessory_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-34.23, -33.2, -67.95]}
      rotation={[-1.45, 0.23, -0.31]}
      scale={71.58}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_front_bottom_part_accessory_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 126.07]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_main_skirt_Primary_0.geometry}
      material={$gltf.materials.Primary}
      position={[0, 0, -176.1]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_main_ring_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, -176.1]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_main_ring_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, -176.1]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_main_ring_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, -176.1]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_main_accessory_31_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-0.46, 29.75, 184.14]}
      rotation={[-1.16, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_main_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, -176.1]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_main_part_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, -162.63]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.Plane009_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-0.54, 0, -140.58]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_main_part_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, -176.1]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.engines_main_part_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, -162.63]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.fuel_tanks_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-28.54, 27.58, -37.38]}
      rotation={[0, 0, -0.77]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_topdown_accessory_12_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-22.73, 45.12, -3.43]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_accessory_61_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-46.07, -8.47, -70.9]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_accessory_62_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-44.66, -0.01, -69.78]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.handles_9_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, -74.3]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.handles_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-38.72, 31.11, -75.5]}
      rotation={[-Math.PI / 2, Math.PI / 4, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.door_rear_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-45.6, 0, -46.18]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.door_rear_accessory_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-44.45, 13.36, -46.44]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_accessory_5_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-43.59, -14.96, -68.98]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_accessory_3001_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-46.89, 7.16, -20.07]}
      rotation={[-2.44, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_side_accessory_22_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-46, 21.68, -3.43]}
      rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_accessory_4001_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-39.41, -3.37, -4.69]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.generators_topdown_accessory_21_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-22.71, -45.11, -3.43]}
      rotation={[Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.handles_10_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[1.57, 7.72, 235.55]}
      rotation={[-1.16, Math.PI / 2, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.handles_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.24, 24.25, 196.38]}
      rotation={[-2.74, 0, Math.PI / 2]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.handles_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.24, 31.36, 179.49]}
      rotation={[-2.74, 0, Math.PI / 2]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.handles_4_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.24, 35.93, 155.97]}
      rotation={[Math.PI, 0, Math.PI / 2]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.handles_5_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.24, 35.93, 147.03]}
      rotation={[Math.PI, 0, Math.PI / 2]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.handles_8_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[7.33, 36.11, 160.73]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_12_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-49.08, 0.44, 101.8]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_9_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-49.08, 4.25, 101.8]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_8_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-58.45, 5.18, 101.52]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_101_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-49.08, -0.23, 101.8]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_102_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-49.08, 0.44, 101.8]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_103_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-49.08, 0.44, 101.8]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_11_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-49.08, 0.01, 101.8]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_111_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-49.08, 0.01, 101.8]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.thruster_8_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-15.8, -0.27, 235.33]}
      rotation={[-0.46, -0.5, 0.06]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.handles_6_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-10.04, 54.4, 42.78]}
      rotation={[0, 0, -Math.PI / 2]}
      scale={112.08}
    />
    <T.Mesh
      geometry={$gltf.nodes.handles_7_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-10.04, 54.4, 62.4]}
      rotation={[0, 0, -Math.PI / 2]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.door_cover_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, -137.48]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_torpedo_bay_front_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_torpedo_bay_accessory_4_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[5.42, 37, 107.69]}
      rotation={[-1.65, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_torpedo_bay_accessory_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[5.42, 0, 99.75]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_torpedo_bay_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_torpedo_bay_accessory_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, -0.26, 56.4]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_7_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-54.7, 17.8, 63.57]}
      rotation={[-Math.PI / 2, Math.PI / 3, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_front_bottom_part_accessory_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0.09, 126.07]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.thruster_9_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0.06, -9.48, 235.95]}
      rotation={[0.73, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.thruster_7_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-21.25, -0.43, 224.78]}
      rotation={[-0.18, -1.22, 0.29]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.thruster_10_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-0.05, -10.72, 226.11]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={201.83}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-12.94, -21.8, 246.04]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_2_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-13.58, -21.89, 246.04]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_2_accessory_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.36, -21.8, 265.61]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-18.04, -21.8, 245.39]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_3_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[20.93, -21.02, 284.01]}
      rotation={[0, 0, 0.49]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_2_accessory_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-12, -23.43, 252.55]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_1_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-18.04, -21.8, 245.39]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_4_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[25.55, -21.34, 260.07]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_4_accessory_11_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[25.82, -21.81, 260.07]}
      rotation={[-Math.PI / 2, 1.05, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_4_accessory_14_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[24.77, -21.81, 260.07]}
      rotation={[Math.PI / 2, -1.05, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_4_accessory_15_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[25.04, -21.34, 260.07]}
      rotation={[-Math.PI / 2, -Math.PI / 3, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_4_accessory_12_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[25.55, -22.26, 260.07]}
      rotation={[Math.PI / 2, Math.PI / 3, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_4_accessory_13_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[25.04, -22.26, 260.07]}
      rotation={[Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 126.07]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[10.56, -21.99, 203.45]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[10.56, -21.99, 206.6]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[10.56, -21.99, 209.74]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_4_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[13.02, -21.99, 216.89]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_5_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[13.02, -21.99, 220]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_6_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[13.02, -21.99, 223.11]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_7_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[13.02, -21.99, 226.23]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_8_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[13.02, -21.99, 229.34]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_9_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[13.02, -21.99, 232.45]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_10_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[13.02, -21.99, 235.56]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_11_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[13.02, -21.99, 238.55]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_12_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[13.02, -21.99, 241.66]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_13_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[13.02, -21.99, 244.78]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_14_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[10.56, -21.99, 251.02]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_15_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[10.56, -21.99, 254.14]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_16_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[10.56, -21.99, 257.26]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_17_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[10.56, -21.99, 260.38]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_18_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[10.56, -21.99, 263.31]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_19_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-9.29, -21.99, 246.42]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_20_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-9.29, -21.99, 243.3]}
      rotation={[-Math.PI / 2, 0, Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_21_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-9.29, -21.99, 240.18]}
      rotation={[-Math.PI / 2, 0, Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_22_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-9.29, -21.99, 237.06]}
      rotation={[-Math.PI / 2, 0, Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_23_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.75, -21.99, 229.41]}
      rotation={[-Math.PI / 2, 0, Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_24_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.75, -21.99, 226.3]}
      rotation={[-Math.PI / 2, 0, Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_25_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.75, -21.99, 223.19]}
      rotation={[-Math.PI / 2, 0, Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_26_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.75, -21.99, 220.08]}
      rotation={[-Math.PI / 2, 0, Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_27_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.75, -21.99, 216.96]}
      rotation={[-Math.PI / 2, 0, Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_28_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.75, -21.99, 213.85]}
      rotation={[-Math.PI / 2, 0, Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_29_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.75, -21.99, 210.74]}
      rotation={[-Math.PI / 2, 0, Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_ribs_30_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-9.29, -21.99, 203.07]}
      rotation={[-Math.PI / 2, 0, Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_9_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[19.25, -25.63, 231.12]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_holders_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.52, -19.5, 255.68]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_antenna_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-11.52, -19.5, 254.32]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_holders_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-10.6, -21.59, 263.46]}
      rotation={[-Math.PI / 2, 1.04, 0]}
      scale={[62.71, 120.24, 62.71]}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_antenna_7001_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-10.6, -21.59, 263.46]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_antenna_8_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-14.27, -23.89, 259.2]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_holders_8_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-14.27, -23.89, 260.59]}
      rotation={[Math.PI / 2, -0.01, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[20.44, -21.8, 292.31]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_3_accessory_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[20.44, -21.8, 292.31]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_6_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-12.09, -18.3, 241.63]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_7_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 126.26]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-16.85, -18.27, 238.49]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_17_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[19.86, -18.2, 253.61]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_20_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[19.76, -18.2, 257.61]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_8_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, 126.07]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_15_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[10.58, -18.21, 253.99]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_14_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[10.58, -18.21, 258.02]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_16_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[9.87, -18.2, 262.95]}
      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[19.44, -18.27, 248.71]}
      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      scale={119.58}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_12_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[13.03, -18.36, 222.6]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={123.71}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_11_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[13.03, -18.36, 225.62]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={123.71}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_10_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[13.03, -18.36, 227.99]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={123.71}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[19.75, -18.27, 232.72]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={119.58}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_13_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0.2, 0, 126.07]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_5_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[24.54, -19.17, 225.79]}
      rotation={[-Math.PI / 2, 0.38, -Math.PI]}
      scale={119.58}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_4_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[24.54, -19.17, 217.52]}
      rotation={[-Math.PI / 2, 0.38, -Math.PI]}
      scale={119.58}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_18_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[22.9, -18.78, 249.63]}
      rotation={[-Math.PI / 2, -0.13, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_holders_accessory_19_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[22.9, -18.78, 257.83]}
      rotation={[-Math.PI / 2, -0.13, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_holders_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-16.27, -21.83, 262.35]}
      rotation={[-Math.PI / 2, 1.04, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_antenna_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-16.25, -21.82, 259.25]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_holders_4_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[19.06, -24.15, 269.7]}
      rotation={[Math.PI / 2, 0.01, Math.PI]}
      scale={150.45}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_antenna_4_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[19.05, -24.16, 269]}
      rotation={[0, 0, 1.05]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_holders_5_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[19.04, -19.3, 277.05]}
      rotation={[-Math.PI / 2, -1.05, 0]}
      scale={150.45}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_antenna_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[19.02, -19.27, 276.31]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_holders_6_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[23.02, -21.83, 274.01]}
      rotation={[-Math.PI / 2, 1.04, 0]}
      scale={136.5}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_antenna_5_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[23.05, -21.82, 270.52]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_4_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[25.3, -21.8, 275.34]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_holders_7_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[25.83, -20.87, 275.91]}
      rotation={[-Math.PI / 2, -0.01, 0]}
      scale={77.84}
    />
    <T.Mesh
      geometry={$gltf.nodes.antenna_mini_antenna_6_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[25.83, -20.87, 272]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_41_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-56.89, -6.26, 35.15]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_42_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-56.92, -6.26, 32.13]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_43_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-56.93, -6.26, 30.62]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_44_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-56.91, -6.26, 33.64]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_45_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-56.94, -6.26, 29.11]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_46_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-56.95, -6.26, 27.6]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_47_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-56.96, -6.26, 26.09]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_48_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-56.97, -6.26, 24.58]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_middle_side_accessory_49_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[-56.98, -6.26, 23.07]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_accessory_1_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[42.54, 0, -46.34]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_accessory_2_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[42.55, 5.66, -33.3]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_accessory_3_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[42.24, 2.36, -53.43]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_accessory_4_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[42.55, 5.66, -33.3]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.Plane001_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, -140.58]}
      rotation={[-Math.PI / 2, Math.PI / 4, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.Plane002_Secondary_0.geometry}
      material={$gltf.materials.Secondary}
      position={[0, 0, -140.58]}
      rotation={[-Math.PI / 2, -Math.PI / 4, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_rear_sides_1_Primary_0.geometry}
      material={$gltf.materials.Primary}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_main001_Primary_0.geometry}
      material={$gltf.materials.Primary}
      position={[0, 0, -103.14]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.hull_main002_Primary_0.geometry}
      material={$gltf.materials.Primary}
      position={[-12.82, -231.06, -46.23]}
      rotation={[Math.PI, -Math.PI / 2, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.Text_Tachi_Texts_0.geometry}
      material={$gltf.materials.Texts}
      position={[-0.06, -0.01, -103.14]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.Text_MCRN_Texts_0.geometry}
      material={$gltf.materials.Texts}
      position={[0, 0.01, 56.71]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.Text_158_right_Texts_0.geometry}
      material={$gltf.materials.Texts}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.Text_NAVY_right_Texts_0.geometry}
      material={$gltf.materials.Texts}
      position={[0, 0, 56.71]}
      rotation={[-Math.PI / 2, 0, -Math.PI]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.Text_158_left_Texts_0.geometry}
      material={$gltf.materials.Texts}
      position={[0, 0, 22.25]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={$gltf.nodes.Text_NAVY_left_Texts_0.geometry}
      material={$gltf.materials.Texts}
      position={[0, 0, 22.25]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />

    <slot {ref} />
  </Three>
{/if}
